#!/bin/bash

# Quick Commands Cheat Sheet für Bambu Discord Bot

echo "╔════════════════════════════════════════════════════════╗"
echo "║     Bambu Discord Bot - PM2 Schnellbefehle            ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""
echo "🚀 Start & Stop:"
echo "  npm run pm2:start      - Bot starten"
echo "  npm run pm2:stop       - Bot stoppen"
echo "  npm run pm2:restart    - Bot neustarten"
echo "  npm run pm2:delete     - Bot entfernen"
echo ""
echo "📊 Monitoring:"
echo "  npm run pm2:status     - Status anzeigen"
echo "  npm run pm2:logs       - Logs folgen"
echo "  pm2 monit              - Live Dashboard"
echo ""
echo "🔄 Autostart:"
echo "  pm2 startup            - Autostart einrichten"
echo "  pm2 save               - Konfiguration speichern"
echo "  pm2 unstartup          - Autostart entfernen"
echo ""
echo "📝 Logs:"
echo "  pm2 logs bambu-discord-bot --lines 100"
echo "  pm2 flush              - Logs löschen"
echo "  tail -f logs/combined.log"
echo ""
echo "🔧 Wartung:"
echo "  pm2 reset bambu-discord-bot  - Statistiken zurücksetzen"
echo "  pm2 reload bambu-discord-bot - Zero-Downtime Reload"
echo "  pm2 describe bambu-discord-bot - Details anzeigen"
echo ""
